repository_type: pipeline

nf_core_version: 3.2.0

lint:
  files_unchanged:
    - .github/CONTRIBUTING.md
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - .github/CONTRIBUTING.md
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - CODE_OF_CONDUCT.md
    - assets/nf-core-hydroscope-nf_logo_light.png
    - docs/images/nf-core-hydroscope-nf_logo_light.png
    - docs/images/nf-core-hydroscope-nf_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
  nextflow_config:
    - process.cpus
    - process.memory
    - process.time
    - custom_config
    - params.custom_config_version
    - params.custom_config_base
    - manifest.name
    - manifest.homePage
    - validation.help.beforeText
    - validation.help.afterText
    - validation.summary.beforeText
    - validation.summary.afterText
  multiqc_config: false
  files_exist:
    - .github/workflows/branch.yml
    - .github/workflows/ci.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - conf/igenomes.config
    - assets/multiqc_config.yml
    - .github/workflows/branch.yml
    - .github/workflows/ci.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - assets/multiqc_config.yml
    - CODE_OF_CONDUCT.md
    - assets/nf-core-hydroscope-nf_logo_light.png
    - docs/images/nf-core-hydroscope-nf_logo_light.png
    - docs/images/nf-core-hydroscope-nf_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  readme:
    - nextflow_badge
  included_configs: false

template:
  org: GENPATH-bioinformatics
  name: hydroscope-nf
  description: A utility pipeline for automation of various wastewater suveillance
    tasks
  author: '@lisa-khanya, @abhi18av'
  version: 1.0.0dev
  force: true
  outdir: hydroscope-nf
  skip_features:
    - ci
    - igenomes
    - github_badges
    - nf_core_configs
    - gitpod
    - codespaces
    - multiqc
    - fastqc
  is_nfcore: false
